exec eww open barlaptop
exec eww open background

exec kitten panel --edge=none --lines 30 --columns 60 --margin-left 1550 --margin-top 700 -o font_size=11 -o background_opacity=0 fish -c "cbonsai -S -w 10 -b 2 -t 6"
